# Generated by Django 6.0.2 on 2026-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.CharField(choices=[('pending', 'pendiente'), ('in_process', 'en proceso'), ('served', 'servido'), ('paid', 'pagado')], default='pending', max_length=20),
        ),
    ]
