# Generated by Django 6.0.2 on 2026-02-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
